# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :trusty do |c|
    c.vm.hostname  = 'itamae-trusty'
    c.vm.hostname += "-#{ENV['WERCKER_BUILD_ID']}" if ENV['WERCKER_BUILD_ID']
    c.vm.provider :virtualbox do |provider, override|
      override.vm.box = "ubuntu/trusty64"
      override.vm.provision :shell, inline: <<-EOC
  cat /etc/apt/sources.list | sed -e 's|http://[^ ]*|mirror://mirrors.ubuntu.com/mirrors.txt|g' > /tmp/sources.list
  if !(diff -q /etc/apt/sources.list /tmp/sources.list); then
    mv /tmp/sources.list /etc/apt/sources.list
    apt-get update
  fi
      EOC
    end

    c.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = '~/.ssh/id_rsa.vagrant'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

      provider.ssh_key_name = ENV['WERCKER'] ? 'vagrant/wercker/itamae' : 'Vagrant'
      provider.token = ENV['DIGITALOCEAN_TOKEN']
      provider.image = 'ubuntu-14-04-x64' # ubuntu
      provider.region = 'nyc3'
      provider.size = '512mb'
    end
  end
end
