# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define :xenial do |c|
    c.vm.hostname  = 'itamae-xenial'
    c.vm.hostname += "-#{ENV['WERCKER_BUILD_ID']}" if ENV['WERCKER_BUILD_ID']
    c.vm.provider :virtualbox do |provider, override|
      override.vm.box = "ubuntu/xenial64"
    end

    c.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = '~/.ssh/id_rsa.vagrant'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

      provider.ssh_key_name = ENV['WERCKER'] ? 'vagrant/wercker/itamae' : 'Vagrant'
      provider.token = ENV['DIGITALOCEAN_TOKEN']
      provider.image = 'ubuntu-16-04-x64' # ubuntu
      provider.region = 'nyc3'
      provider.size = '512mb'
    end
  end
end
