name: test_main

on:
  workflow_call:
    inputs:
      ruby:
        required: true
        type: string
      rubyopt:
        required: false
        type: string
        default: ""
      skip_http_request_test:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true
          bundler: default

      - run: bundle update

      - run: bundle exec rake spec:unit
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - name: Slack Notification (not success)
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          inputs: ${{ toJson(inputs) }}

  integration-docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        image:
          - ubuntu:trusty

    env:
      TEST_IMAGE: ${{ matrix.image }}
      SKIP_HTTP_REQUEST_TEST: ${{ inputs.skip_http_request_test }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true
          bundler: default

      - run: bundle update

      - run: bundle exec rake spec:integration:docker:boot
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - run: bundle exec rake spec:integration:docker:provision
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

          # FIXME: avoid error for "Command `chmod 777 /tmp/itamae_tmp` failed. (exit status: 1)"
          ITAMAE_TMP_DIR: /var/tmp/itamae_tmp

      - run: bundle exec rake spec:integration:docker:serverspec
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - run: bundle exec rake spec:integration:docker:clean_docker_container
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - name: Slack Notification (not success)
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          matrix: ${{ toJson(matrix) }}

  integration-local:
    runs-on: ubuntu-latest

    # NOTE: When ruby is 2.5, tests run on buster. But buster is already EOL and didn't work apt-get
    if: ${{ inputs.ruby >= '2.6' }}

    env:
      SKIP_HTTP_REQUEST_TEST: ${{ inputs.skip_http_request_test }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true
          bundler: default

      - run: bundle update

      - run: bundle exec rake spec:integration:local:main
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - run: bundle exec rake spec:integration:local:ordinary_user
        env:
          RUBYOPT: ${{ inputs.rubyopt }}

      - name: Slack Notification (not success)
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          inputs: ${{ toJson(inputs) }}
